### ISSUE TITLE
Offline mode broken?

### ISSUE THREAD

**Issue by howyp** [hmrc/service-manager#37]
Since upgrading to 0.0.30, I see the error `Unexpected exception: local variable 'binaryConfig' referenced before assignment` when running in offline mode.

Stack trace:
```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/servicemanager/server/smserverlogic.py", line 172, in process_request
    self._start_services_for_test(orchestration_services, service_mapping_ports)
  File "/Library/Python/2.7/site-packages/servicemanager/server/smserverlogic.py", line 240, in _start_services_for_test
    self._start_services(orchestration_services, service_mapping_ports, None)
  File "/Library/Python/2.7/site-packages/servicemanager/server/smserverlogic.py", line 203, in _start_services
    self.context.start_service(service_name, run_from, proxy, classifier, service_mapping_ports, port, admin_port, version, append_args)
  File "/Library/Python/2.7/site-packages/servicemanager/smcontext.py", line 355, in start_service
    service_process_id = service_starter.start()
  File "/Library/Python/2.7/site-packages/servicemanager/service/smjvmservice.py", line 29, in start
    return self.start_from_binary()
  File "/Library/Python/2.7/site-packages/servicemanager/service/smplayservice.py", line 98, in start_from_binary
    unzip_dir = self._unpack_play_application(SmArtifactRepoFactory.get_play_app_extension(binaryConfig))
```

**Comment by rpowis** [comment]
Fixed in #39
