### ISSUE TITLE
Using --showcmdfor causes runtime error

### ISSUE THREAD

**Issue by hughfdjackson** [hmrc/service-manager#48]
When I attempt to find the command for my service, I get the following error: 

```
➜  servicemanager  sm --showcmdfor THIRD_PARTY_DEVELOPER
The parameters you provided would start the following services using the following commands:
Traceback (most recent call last):
  File "/usr/local/bin/sm", line 177, in <module>
    _process_command()
  File "/usr/local/bin/sm", line 154, in _process_command
    cmd = actions.get_start_cmd(context, service_name, args.fatjar, args.release, args.proxy, actions.overridden_port(args.showcmdfor, args.port), args.appendArgs)
  File "/Library/Python/2.7/site-packages/servicemanager/actions/actions.py", line 49, in get_start_cmd
    starter = context.get_service_starter(service_name, run_from, proxy, port=port, version=version, appendArgs=appendArgs)
TypeError: get_service_starter() got an unexpected keyword argument 'appendArgs'
```

The problem seems to boil down to `get_service_starter` being called with `appendArgs=appendArgs`, whereas the definition of `get_service_starter` expects an `append_args` parameter.

**Comment by jakobgrunig** [comment]
This seems to be working now, please re-open if the issue is still there
